# Testing Integrity

In [2]:
%load_ext sql
import sqlite3

### Connect Database

In [7]:
%sql sqlite:///CourseData.db
conn = sqlite3.connect('CourseData.db')

In [8]:
%%sql 
SELECT term,crn,location, day, start 
FROM IMPORT_COURSE_MEETINGS
GROUP BY term,crn,location, day, start
HAVING COUNT(*)>1;

 * sqlite:///CourseData.db
Done.

[('Fall2014', 73073, 'MCA 102', 'M', '2014-09-08T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-09-15T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-09-22T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-09-29T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-10-06T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-10-20T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-10-27T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-11-03T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-11-10T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-11-17T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-11-24T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-12-01T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-12-08T18:30:00'),
 ('Fall2014', 73073, 'MCA 102', 'M', '2014-12-15T18:30:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-09-03T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-09-10T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-09-17T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-09-24T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-10-01T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-10-08T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-10-15T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-10-22T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-10-29T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-11-05T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-11-12T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-11-19T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-11-26T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-12-03T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-12-10T17:00:00'),
 ('Fall2014', 73188, 'SON 214', 'W', '2014-12-17T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-01-21T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-01-28T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-02-04T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-02-11T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-02-18T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-02-25T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-03-04T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-03-18T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-03-25T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-04-01T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-04-08T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-04-15T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-04-22T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-04-29T17:00:00'),
 ('Spring2015', 32325, 'SON 214', 'W', '2015-05-06T17:00:00')]